name: Deploy app to shinyapps.io using rsconnect

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy-shiny:
    runs-on: macos-latest
    strategy:
      matrix:
        r-version: ['4.1.1']

    steps:
      - uses: actions/checkout@v3
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@f57f1301a053485946083d7a45022b278929a78a
        with:
          r-version: ${{ matrix.r-version }}
      - name: Install shiny
        run: |
          install.packages(c("shiny", "rsconnect"), type = "binary")
        shell: Rscript {0}
      - name: Setup rsconnect
        run: |
          rsconnect::setAccountInfo(name='abohyndoe', token=${{secrets.SHINYAPPS_TOKEN}}, secret=${{secrets.SHINYAPPS_SECRET}})
        shell: Rscript {0}
      - name: Deploy app
        run: |
          rsconnect::deployApp(appName = 'fatldesign-selection-tool')
        shell: Rscript {0}
